### PR TITLE
Readme version 1.1

### PR DESCRIPTION
**Pull request by adirao-projects**
Updated Readme with general implementation rules and internal milestones

### CODE REVIEW

**Review by RMagill46 — DISMISSED** [review]
Adi this is amazing, I love you

**Review by David9Nagy — DISMISSED** [review]

**Review by cherche — COMMENTED** [review]
Please fix some formatting issues. And as you noted, there are some inaccurate statements, e.g., "three other team members".

**Comment by adirao-projects** [comment]
> This is terrible, Adi you suck

:(

**Review by RMagill46 — APPROVED** [review]

**Review by cjwssb687 — APPROVED** [review]
.

**Review by David9Nagy — APPROVED** [review]

**Pull request merged**
